### PR TITLE
Fix/issue 201 - Search bar and button style

### PR DESCRIPTION
**Pull request by DeeJayElly**
Fix/issue 201 - Search bar and button style

### CODE REVIEW

**Comment by a-rukin** [comment]
@DeeJayElly pls - screenshots/links/anything to look except code ))

**Comment by a-rukin** [comment]
image

on the 404 page (in netlify) line with triangle is in a proper color

image

for the header it was switched to the primary one 

why?

**Comment by DominikGuzei** [comment]
@a-rukin i changed the search bar "triangle separator" to the secondary color, is that better?

Bildschirmfoto 2020-02-18 um 15 51 06

It would be a bit more work to match the design exactly (triangle outlines only)

**Comment by a-rukin** [comment]
@DominikGuzei better, yeah, just need to make triangle outlined again)

**Comment by DominikGuzei** [comment]
@a-rukin was that a triangle outline at any point of the project? Will git blame to see if we have something there 👍

**Comment by a-rukin** [comment]
> @a-rukin was that a triangle outline at any point of the project? Will git blame to see if we have something there 👍

well if I'm not mistaken, this is the first time I see it filled )

**Comment by DominikGuzei** [comment]
Ok found a simple solution for the triangle outlines:

**Pull request merged**
