### PR TITLE
Fixing issue 200 - Outdated Browser page styling and missing footer

### LINKED ISSUE #200: Outdated Browser page styling and missing footer
Should be:
https://app.zeplin.io/project/5878c3481bb7631c20cb161a/screen/5d65438ddd6f4cb2bf746a61

### PR DESCRIPTION
**Pull request by DeeJayElly**
Fixes #200 - Outdated Browser page styling and missing footer

screencapture-localhost-4000-outdated-browser-2020-02-20-21_44_59

### CODE REVIEW

**Comment by a-rukin** [comment]
@DeeJayElly this page is not visible in netlify :(

**Comment by DeeJayElly** [comment]
> @DeeJayElly this page is not visible in netlify :(

Try now, it should be available.

**Comment by a-rukin** [comment]
> Looks good to me! 👍 @a-rukin are you satisfied with the browser icon hover effect? (the icon is colored + moved up 3px)

can we remove this 3px movement?)

**Comment by a-rukin** [comment]
@DominikGuzei I see commit, but netlify is not updated. Strange

**Comment by DominikGuzei** [comment]
@a-rukin i did the change blindly on Github, maybe i missed something there - will double check now 👍

**Comment by DominikGuzei** [comment]
@a-rukin @DeeJayElly really weird, i re-added the same fix that @DeeJayElly had (it actually worked but not in PR storybook, so yes @a-rukin it seems like sometimes it's not 100% correctly picking up the changes 🤔 )

**Comment by DominikGuzei** [comment]
Latest state:

**Comment by DeeJayElly** [comment]
> Latest state:
> 

Yeah it was like this from the start for me. I don't know why netifly is kinda acting weird sometimes.

**Pull request merged**
