### PR TITLE
[issue-304] Fix misleading tx amounts

### LINKED ISSUE #304: Explorer Transaction view amounts misleading
I was trying to debug where a change address ended up from the explorer and failed miserably. I ended opening up postgres and doing the queries manually. This is not the transaction I was debugging, but shows the same behavior:
https://explorer.cardano.org/en/transaction/?id=c06157e877c72be85361b0050271310f4b9620b93fd8a84414d2fdea0eb2dc98

My assumption was next to the outputs would be the amounts going to each of the addresses they were next to. This ended up being an incorrect assumption, which I think is a bug.

Here's a list of the queries if it helps I made to get the answer I was looking for (how much ada was sent to the outputs of the transaction):

Get the tx_id:
```
cexplorer=# SELECT * FROM tx WHERE hash=decode('c06157e877c72be85361b0050271310f4b9620b93fd8a84414d2fdea0eb2dc98', 'hex');
   id    |                                hash                                |  block  |  fee   |  out_sum   | size 
---------+--------------------------------------------------------------------+---------+--------+------------+------
 2007257 | \xc06157e877c72be85361b0050271310f4b9620b93fd8a84414d2fdea0eb2dc98 | 4086311 | 179288 | 8284920712 |  225
(1 row)
```

Get the tx inputs:
```
SELECT * FROM tx_in WHERE tx_in_id=2007257;
   id    | tx_in_id | tx_out_id | tx_out_index 
---------+----------+-----------+--------------
 4050460 |  2007257 |   1128450 |            1
 4050461 |  2007257 |   1232938 |            2
```
Get the addresses and values of inputs (these values are what show up in explorer interface):
```
cexplorer=# SELECT * FROM tx_out WHERE tx_id=1128450 AND index=1;
   id    |  tx_id  | index |                           address                           |   value    
---------+---------+-------+-------------------------------------------------------------+------------
 2537868 | 1128450 |     1 | Ae2tdPwUPEZ5P6QnkfF3ZW2QEK7ob5VRocxVpWtDQ1U29jznPWfiKP7eK6c | 1291200000
(1 row)

cexplorer=# SELECT * FROM tx_out WHERE tx_id=1232938 AND index=2;
   id    |  tx_id  | index |                           address                           |   value    
---------+---------+-------+-------------------------------------------------------------+------------
 2787111 | 1232938 |     2 | Ae2tdPwUPEZK4sg8PGJB2RABqwQj4rC4PMUMFxXzsehqYmyp4QdN86qWe3J | 6993900000
(1 row)
```

Get the outputs:
```
cexplorer=# SELECT * FROM tx_out WHERE tx_id=2007257;
   id    |  tx_id  | index |                                                 address                                                  |   value    
---------+---------+-------+----------------------------------------------------------------------------------------------------------+------------
 4635572 | 2007257 |     0 | DdzFFzCqrhsu5wVeit7MKhwCuGRGhy6pra1RuMtuhScF3Tpp9W5rwzLMwjBvAxNcMtBUj9cxeRjKrqUUGs2WXEtLT1MweRZ9XNnDGVbM | 5000000000
 4635573 | 2007257 |     1 | Ae2tdPwUPEZ5P6QnkfF3ZW2QEK7ob5VRocxVpWtDQ1U29jznPWfiKP7eK6c                                              | 3284920712
(2 rows)
```

It seems to be it would make more sense if the values on the right side of the screen were the values in this last query (5000000000 and 3284920712).

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR fixes #304 and #310 by replacing the tx summary component with an improved, mobile-firest version of the tx info comp that displays "from" and "to" addresses + amounts in a less confusing way.

Tx details, mobile:
grafik

Tx details, desktop:
grafik

Address details, mobile:
grafik

Address details, desktop:
grafik

Block summary, desktop:
grafik

### CODE REVIEW

**Comment by DominikGuzei** [comment]
@a-rukin will prepare a design for this change

**Comment by DominikGuzei** [comment]
@a-rukin @rhyslbw @disassembler this PR is ready for review 👍

**Comment by a-rukin** [comment]
image
while testing I found this TX... it's super strange bacause these two input addresses are the same address

**Comment by rhyslbw** [comment]
> while testing I found this TX... it's super strange bacause these two input addresses are the same address

Addresses do not uniquely identify an output, they are just proof of ownership. So with this in mind, your observation would be:

_these two inputs **have** the same address_ ... which is not unexpected.

More info in the [Adrestia User guide](https://input-output-hk.github.io/adrestia/docs/key-concepts/utxo/)

**Comment by a-rukin** [comment]
> Addresses do not uniquely identify an output, they are just proof of ownership. So with this in mind, your observation would be:
> 
> _these two inputs **have** the same address_ ... which is not unexpected.
> 
> More info in the [Adrestia User guide](https://input-output-hk.github.io/adrestia/docs/key-concepts/utxo/)

@rhyslbw My confusion was that we use two rows with two values instead of one with a sum 

It's like: 
_take 2 Jonny's apples from left pocket and take 3 Jonny's apples from exact same left pocket and spread them between Alice and Bob_
but logical would be 
_take 5 Jonny's apples from left pocket and spread them..._

> Addresses do not uniquely identify an output

this just doesn't belong to this question

**Comment by DominikGuzei** [comment]
@a-rukin good observation, I also didn't know that there could be the same address multiple times. @rhyslbw would it make sense to group/sum them or is it somehow important to keep the values separate?

**Comment by rhyslbw** [comment]
@a-rukin @DominikGuzei 
At this point we're simply representing a fundamental data structure of a UTxO-based blockchain. With this in mind, it would however make more sense to label:

- _From addresses_ as **inputs**
- _To addresses_ **outputs**

I think there's room for alternative display, with logical groupings as suggested, however it would be best offered as a complement, because what we have now is valid and exposes the components of a transaction.

**Pull request merged**
