### PR TITLE
[issue-306] Upgrade to Next.js 9.4

### LINKED ISSUE #306: Update to Next.js 9.4
Mainly dev features but pretty awesome: https://nextjs.org/blog/next-9-4

### LINKED ISSUE #312: Epochs not loading from other Epoch page
When you epoch's are searched from another epoch page, the page does not load and the animation remains. 

For example: you type "150" and click on "Epoch 150". The page loads (swiftly), Therafter you type "100", and click on "Epoch 100", the loading animation remains. Only after refreshing the URL, Epoch 100 loads. 

I've not tested this with Transactions.

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR upgrades to Next.js 9.4 with support for preact fast refresh (instant hot reloading component updates during development 🎉 ). I'm pretty sure it also fixes the epoch loading issue (because I fixed another error relating to the epochs loading logic)

fixes #306
fixes #312

### CODE REVIEW

**Comment by rhyslbw** [comment]
@DominikGuzei is this ready for review? You've left a `WIP` label on it, but everything else LGTM. I suggest we remove that label from the system, and just use the native _draft_ feature, as this is more obvious when preparing the PR.

**Comment by DominikGuzei** [comment]
@rhyslbw I was fixing issues with the tests and was waiting for the tests to run for the latest commit before i left, that's why i added the WIP flag 😉 it seems like one of the test runs failed btw.

**Comment by DominikGuzei** [comment]
@rhyslbw I re-added WIP flag because I just found some UX issues when browsing epochs/blocks. The loading UX is not the same as before (check out https://deploy-preview-314--cardano-explorer-mainnet.netlify.app/de/browse-epochs?page=14&perPage=10 and navigate between pages to see what I mean)

**Comment by DominikGuzei** [comment]
@rhyslbw this PR is ready for final release 👍

**Comment by pannenkoekenpan** [comment]
Great work @DominikGuzei and @rhyslbw. Best of luck with everything!

**Pull request merged**
