### PR TITLE
Fixing issue 202 - Erroneous space after ellipsis in long address display

### LINKED ISSUE #202: Erroneous space after ellipsis in long address display
Ellipsis
Should be:
https://app.zeplin.io/project/5878c3481bb7631c20cb161a/screen/5b06e47090d3b1842141a373

### PR DESCRIPTION
**Pull request by DeeJayElly**
Fixes #202 - Erroneous space after ellipsis in long address display

### CODE REVIEW

**Comment by a-rukin** [comment]
Is netlify updated? 
or where I can take a look?

**Comment by DominikGuzei** [comment]
@a-rukin Netlify is automatically updated on any commit, you can see the status in the bottom area

**Comment by DeeJayElly** [comment]
We are still not done here. I found few more issues and working on them @DominikGuzei @a-rukin

**Comment by DominikGuzei** [comment]
@DeeJayElly wait a sec, i also fixed some issues 😅 will push in a minute

**Comment by a-rukin** [comment]
> @a-rukin Netlify is automatically updated on any commit, you can see the status in the bottom area

image

I've asked because it seems like old. And in some other PR it doesn't have so much space here

**Comment by DeeJayElly** [comment]
> > @a-rukin Netlify is automatically updated on any commit, you can see the status in the bottom area
> 
> image
> 
> I've asked because it seems like old. And in some other PR it doesn't have so much space here

@a-rukin @DominikGuzei fixed

screencapture-localhost-4000-block-2020-02-20-20_53_51

**Comment by a-rukin** [comment]
> screencapture-localhost-4000-block-2020-02-20-20_53_51

Niiice

**Pull request merged**
