### PR TITLE
[DDW-867] Implement Block details page design

### PR DESCRIPTION
**Pull request by DeeJayElly**
This PR implemented Block summary component for Block details page.
[YouTrack Ticket](https://iohk.myjetbrains.com/youtrack/issue/DDW-867)

## Screenshots
Screenshot 2019-10-06 21 27 15

## Testing Checklist
- [x] Go to `Block` => `Block Summary` stories on storybook and check if it matches with wireframe

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by gnpf** [comment]
@DeeJayElly In some resolutions, the text exceeds the limits of the title divider. So far I reproduced this on 1024 x 768 and 1024 x 1366:

image

**Comment by yakovkaravelov** [comment]
@DeeJayElly All these PRs have too many git commits history even though each of them is just for one ticket.
Can we clear such things from next PRs?
It's been like so in all PRs so far.

**Comment by DeeJayElly** [comment]
> @DeeJayElly All these PRs have too many git commits history even though each of them is just for one ticket.
> Can we clear such things from next PRs?
> It's been like so in all PRs so far.

Merge requests from other PR's since i had to reuse some things and couldn't wait for other PRs to be merged next. Just pls ignore them and don't worry about them, they will all be merged when we approve and merge all tickets.

**Comment by DeeJayElly** [comment]
> @DeeJayElly In some resolutions, the text exceeds the limits of the title divider. So far I reproduced this on 1024 x 768 and 1024 x 1366:
> 
> image

Fixed

**Comment by gnpf** [comment]
@DeeJayElly The fix for the previous issue looks good. But I am reproducing something new regarding the title.
In some cases, the title splits into two rows. Not sure if these resolutions are supported, but let me know what you think.

image

image

**Comment by DeeJayElly** [comment]
> @DeeJayElly The fix for the previous issue looks good. But I am reproducing something new regarding the title.
> In some cases, the title splits into two rows. Not sure if these resolutions are supported, but let me know what you think.
> 
> image
> 
> image

Fixed

**Pull request merged**
