### PR TITLE
Feature/refined search helper ui

### PR DESCRIPTION
**Pull request by DeeJayElly**
Feature/refined search helper ui

screencapture-localhost-4000-2020-02-26-13_57_31

Screenshot 2020-02-26 13 57 51

screencapture-localhost-4000-2020-02-26-20_41_10

### CODE REVIEW

**Comment by rhyslbw** [comment]
@DeeJayElly please ensure to [link PRs to issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when opening

**Comment by DeeJayElly** [comment]
> Great work! But in storybook the new search suggestions seem to be visually broken:
> Bildschirmfoto 2020-02-26 um 21 15 14

Will recheck and fix

**Comment by a-rukin** [comment]
Do we have an example of this?
image

**Comment by DeeJayElly** [comment]
> Do we have an example of this?
> image

Yes added everything now in storybook

**Comment by DeeJayElly** [comment]
Screenshot 2020-02-27 13 12 55
Screenshot 2020-02-27 13 12 42


@a-rukin @rhyslbw @DominikGuzei

**Comment by a-rukin** [comment]
image
x is not centered

**Comment by DeeJayElly** [comment]
> image
> 
> x is not centered

Fixed

**Comment by a-rukin** [comment]
> > image
> > x is not centered
> 
> Fixed

@DeeJayElly can you pls check that 600 font weight corresponds to semibold here

**Comment by rhyslbw** [comment]
@DeeJayElly I'm still seeing a misalignment in Storybook
Screenshot from 2020-02-28 09-42-57

**Comment by DeeJayElly** [comment]
> @DeeJayElly I'm still seeing a misalignment in Storybook
> Screenshot from 2020-02-28 09-42-57

I am seeing this:

https://www.dropbox.com/s/w0pzrq7mkclk2uf/Screenshot%202020-02-28%2000.37.22.png?dl=0

**Comment by DeeJayElly** [comment]
> Great work! But in storybook the new search suggestions seem to be visually broken:
> Bildschirmfoto 2020-02-26 um 21 15 14

Fixed

**Comment by DominikGuzei** [comment]
Still not solved for me (just checked in Firefox), i noticed that the mis-alignment happens when you change the screen size:

**Comment by DeeJayElly** [comment]
> Still not solved for me (just checked in Firefox), i noticed that the mis-alignment happens when you change the screen size:
> 

Fixed

**Comment by a-rukin** [comment]
image
on the search bar (around 780px width) there is a missaligment on the live version

**Comment by DeeJayElly** [comment]
> image
> 
> on the search bar (around 780px width) there is a missaligment on the live version

Fixed

**Comment by a-rukin** [comment]
image
x position broken again 
move it 1px to top

**Comment by rhyslbw** [comment]
@DeeJayElly Please address the styling as a priority and pass to @DominikGuzei for the client application logic. It's hard to separate the component and application logic here, and we can't merge it as an incomplete feature.

**Comment by DeeJayElly** [comment]
> image
> 
> x position broken again move it 1px to top

Fixed

**Comment by DominikGuzei** [comment]
Suggestions are not correctly positioned on sub-pages with the shrinked search bar layout:
Bildschirmfoto 2020-03-04 um 20 37 30

**Comment by DeeJayElly** [comment]
> Suggestions are not correctly positioned on sub-pages with the shrinked search bar layout:
> Bildschirmfoto 2020-03-04 um 20 37 30

Fixed

**Comment by a-rukin** [comment]
image
@DeeJayElly @DominikGuzei do we shrink sizes of search when less than some px width?

**Comment by DeeJayElly** [comment]
> image
> 
> @DeeJayElly @DominikGuzei do we shrink sizes of search when less than some px width? I mean rest is not smaller, all stays the same except header

Everything stays the same, and the size is always container size

**Comment by a-rukin** [comment]
> Everything stays the same, and the size is always container size

Compare 

image

image

if you can't catch font changes, button is a big indicator ))

**Comment by DeeJayElly** [comment]
> > Everything stays the same, and the size is always container size
> 
> Compare
> 
> image
> 
> image
> 
> if you can't catch font changes, button is a big indicator ))

Screenshot 2020-03-06 14 14 01
Screenshot 2020-03-06 14 13 49

**Comment by a-rukin** [comment]
checking

**Comment by a-rukin** [comment]
image
is this a normal behaviour?

**Comment by DeeJayElly** [comment]
> image
> 
> is this a normal behaviour?

Shouldn't be. I am rechecking now...

**Comment by a-rukin** [comment]
> > image
> > is this a normal behaviour?
> 
> Shouldn't be. I am rechecking now...

When I continue typing it shows suggest again

**Comment by DeeJayElly** [comment]
> > > image
> > > is this a normal behaviour?
> > 
> > 
> > Shouldn't be. I am rechecking now...
> 
> When I continue typing it shows suggest again

Check it now, it should be ok.

**Pull request merged**
